[package]
name = "tscripts_rs"
version = "1.3.0"
edition = "2024"

[[bin]]
name = "translations_manager"
path = "src/main.rs"

[dependencies]
aho-corasick = "1.1.4"
anyhow = "1.0.100"
clap = { version = "4.5.51", features = ["derive", "wrap_help"] }
dialoguer = { version = "0.12.0", features = ["history"] }
directories = "6.0.0"
itertools = "0.14.0"
jieba-rs = "0.8.1"
prettytable-rs = "0.10.0"
rayon = "1.11.0"
regex = "1.12.2"
sanitize-filename = "0.6.0"
serde = { version = "1.0.228", features = ["derive"] }
simd-json = { version = "0.17.0", features = ["beef"] }
strum = { version = "0.27.2", features = ["derive"] }
toml = "0.9.8"
unicode-normalization = "0.1.25"
path-clean = "1.0.1"
textwrap = "0.16.2"
include_dir = "0.7.4"
console = "0.16.1"
bk-tree = "0.5.0"
arboard = "3.6.1"
time = { version = "0.3.44", features = ["macros", "formatting"] }
jwalk = "0.8.1"
threadpool = "1.8.1"
num_cpus = "1.17.0"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_System_Console"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
